LANDSAT_8 = "LANDSAT/LC08/C01/T1_RT"
LANDSAT_7 = "LANDSAT/LE07/C01/T1_RT"
SENTINEL_2 = "COPERNICUS/S2"
ALOS_2 = "JAXA/ALOS/AVNIR-2/ORI"

ALL_SATELLITE = []
ALL_SATELLITE.append([LANDSAT_8,LANDSAT_7,SENTINEL_2,ALOS_2])